### ISSUE TITLE
Elegir responsables por curso

### ISSUE THREAD

**Issue by mroman42** [libreim/calendar-deprecated#3]
Estaría bien que hubiera más de una persona en cada curso que vigilara que el calendario está correcto. Creo que en primero lo hacían ya de facto @jesusjmma y @pbaeyens (confirmadme si podéis que era así). ¿Alguien se ofrece para cada curso?
- [x] **Primero:** @jmml97 y @fjsaezm 
- [x] **Segundo:** @jesusjmma y @pbaeyens 
- [ ] **Tercero:** @andreshp 
- [X] **Cuarto:** @fdavidcl y @SergioPadilla
- [ ] **Quinto:** @analca3

**Comment by mx-psi** [comment]
Yo lo seguiría haciendo para segundo, y supongo que @jesusjmma también. Para primero podría preguntar @makixun por el grupo de WhatsApp que tienen si alguien se ofrece.

**Comment by 29antonioac** [comment]
De quinto sería un poco cacao (hay 5 ramas elegibles), aunque podría dedicarme a la de Computación y Sistemas Inteligentes, que es la que voy a hacer.

**Comment by jmml97** [comment]
Hola, yo soy de primero. Puedo organizar yo el calendario pero tenéis que explicarme un poco como va.

**Comment by mx-psi** [comment]
@jmml97 La idea es ~~crear un calendario en Google Calendar, [compartirlo](https://support.google.com/calendar/answer/37082?hl=es) de forma pública y~~ (parece que Mario se te ha adelantado con esto xD)  mantenerlo con exámenes finales y  parciales, tutorías grupales, entregas de trabajos y otras cosas que se salgan del horario normal de clase. Lo ideal sería que buscaras al menos a alguien más que lo mantenga. Una vez esté creado lo insertaremos con el resto.

**Comment by mroman42** [comment]
Vale, por ahora os apunto y en cuanto estén dos, creo los calendarios, los coloco en la página y doy permisos.

**Comment by jmml97** [comment]
Entiendo. Pues en cuanto pueda (y tenga fechas) haré el calendario. ¿Os lo paso entonces por aquí?

**Comment by mx-psi** [comment]
Creo entender que ya lo hace @M42 y te lo pasa él.

**Comment by mroman42** [comment]
Sí, pero realmente da igual quien lo haga, la única ventaja que le veo a hacerlos en la cuenta de google del dgiim es que se vean y se controlen todos de una vez. Vamos a esperar a tener dos personas y lo hacemos.

**Comment by 29antonioac** [comment]
Perfecto, a la espera estoy entonces del calendario.

**Comment by jesusjmma** [comment]
Ya he visto que @pbaeyens  ha hablado por mí. Efectivamente él y yo nos podemos hacer cargo del calendario de segundo.

**Comment by fjsaezm** [comment]
Hola, soy Javi Sáez de 1º y he hablado con @jmml97 para organizar yo el calendario con él!

**Comment by mx-psi** [comment]
Genial! Ya estás apuntado arriba :shipit:

**Comment by fdavidcl** [comment]
Dice @SergioPadilla que puede echar una mano a administrar el de 4°. Lo añado a la lista.

**Comment by Darth-ATA** [comment]
@analca3 estas son las fechas de mis examenes de 5º:

Enero/Febrero
29/01/16 Historia de las matemáticas
11/02/16 Procesadores de Lenguajes

Junio/Julio
15/06/16 TSI
28/06/16 IC
01/07/16 AA
06/07/16 MH

Gracias 
:+1:

**Comment by oxcar103** [comment]
Una cuestión que me acaba de surgir, las asignaturas optativas de informática, como se pueden cursar tanto en 4º como en 5º, ¿deberían aparecer _todas_(*) en ambos calendarios, no?
¿Cómo se organizará para tenerlo actualizado e idéntico en ambos calendarios, a mano?

(*) Nótese que ese _todas_, puede acabar siendo 5 asignaturas porque la mayoría creo que escogimos la misma mención.

**Comment by 29antonioac** [comment]
Podemos preocuparnos de eso el segundo cuatrimestre XD, aunque lo más sencillo es que cada cual meta la asignatura en su calendario.

Si el cuatrimestre que viene coincidimos tú y yo en una asignatura obligatoria de rama de 3°, pues tú actualizas el de 4° y yo el de 5° XD. Lo más sencillo es. Meter muchos calendarios lo que hará será liarnos!

**Comment by mroman42** [comment]
Cierro esta issue y reabro otra actualizada para este curso.
