### ISSUE TITLE
Enlazar el calendario

### ISSUE THREAD

**Issue by mroman42** [libreim/calendar-deprecated#4]
Para que sea útil tendrá que estar enlazado con el resto de la página. No sé dónde encajaría mejor, quizá en los recursos o en un enlace desde el blog o el foro.

**Comment by jesusjmma** [comment]
Están ya enlazados los de 2º y 4º ¿no? Aunque no sé cómo se verán desde el ordenador, pero desde el iPad se ve uno de ellos encima del otro.

**Comment by fdavidcl** [comment]
@M42 Creo que el calendario y el foro deberían ir de la mano, porque son las cosas propias del grado y menos 'divulgativas'. Añadiré enlaces entre ellos.

@jesusjmma Imagino que te refieres a que se ven a una columna, es lo esperable en una tablet. En el ordenador se verá a dos columnas. La vista depende del tamaño y resolución de la pantalla:  
![dgiimcalhor](https://cloud.githubusercontent.com/assets/909629/10026983/e7bc30ce-6164-11e5-83d5-7ca788505032.png)

**Comment by jesusjmma** [comment]
Me refiero, literalmente, a que uno se ve encima del otro. Se tapa la mitad de un calendario. ![image](https://cloud.githubusercontent.com/assets/10512294/10039824/20651bea-61d6-11e5-9444-61e4807530a9.png)

**Comment by fdavidcl** [comment]
@jesusjmma Oops, vaya, tendremos que revisar eso. Creo que tengo una idea de lo que está pasando. Gracias por la captura de pantalla, seguimos tratando esto en #6 para no desviar la conversación :)

**Comment by mroman42** [comment]
Creo que si vamos a seguir manteniéndolo, habría que enlazarlo desde Awesome, debajo de los apuntes.
